# Generated by Django 5.2.16 on 2026-08-07 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelBlock',
        ),
    ]
