# Generated by Django 5.2.16 on 2026-07-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='alt_text',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
