# Generated by Django 5.2.16 on 2026-07-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lookup_code', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('plus_one_allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField()),
                ('meal_choice', models.CharField(blank=True, max_length=100)),
                ('plus_one_attending', models.BooleanField(default=False)),
                ('plus_one_name', models.CharField(blank=True, max_length=200)),
                ('plus_one_meal', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rsvp.guest')),
            ],
        ),
    ]
